version: '3.3'

services:

    mysql:
        image: mariadb:latest
        restart: always
        volumes:
          - ./src/task/db/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql
        environment:
          MYSQL_ROOT_PASSWORD: MyDBRoot123
          MYSQL_DATABASE: ShiyunTask
          MYSQL_USER: php
          MYSQL_PASSWORD: php
        networks:
          - mynet

    myredis:
        image: redis:latest
        restart: always
        networks:
          - mynet

    myphp:
        build:
          context: .
          dockerfile: ./src/php/dockerfile
        depends_on:
          - mysql
          - myredis
        links:
          - mysql
          - myredis
        restart: always
        ports:
          - "9000"
        volumes:
          - ./src/:/var/www/html
        networks:
          - mynet

    mynginx:
      depends_on:
        - myphp
      links:
        - myphp
      image: nginx
      restart: always
      ports:
        - "8080:80"
      volumes:
        - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
        - ./src/:/var/www/html
      networks:
          - mynet

    phpMyAdmin:
      depends_on:
        - mysql
      links:
        - mysql
      restart: always
      image: phpmyadmin/phpmyadmin
      ports:
        - "8082:80"
      environment:
        PMA_HOST: mysql
      networks:
          - mynet

networks:
    mynet:
      driver: bridge
